export const HomeProjects = [
    {
        title: 'YelpCamp',
        description: 'YelpCamp is a full-stack web application designed for campground enthusiasts. It serves as a platform for users to explore, review, and share information about campgrounds from around the world. The application empowers users to discover new camping destinations, leave reviews based on their experiences, and contribute by adding new campgrounds.',
        image: 'https://res.cloudinary.com/di22m4v3n/image/upload/q_auto,f_auto/v1732361740/portfolio/yelpcamp_hjllcf.png',
        tags: ['Express', 'Node.js', 'MongoDB'],
        githubUrl: 'https://github.com/viniduminsara/YelpCamp',
        liveUrl: 'https://yelpcamp-g30m.onrender.com/',
    },
    {
        title: 'Shoes Management System',
        description: 'Hello Shoes Management System is a comprehensive web application designed to manage the operations of a shoe store. The system allows different types of users (regular and admin) to log in and perform specific actions based on their roles.',
        image: 'https://res.cloudinary.com/di22m4v3n/image/upload/q_auto,f_auto/v1732361737/portfolio/shoe-management-system_huhukc.png',
        tags: ['Java', 'Spring Boot', 'Tailwind CSS'],
        githubUrl: 'https://github.com/viniduminsara/Hello_Shoe_Management_System_Backend',
        liveUrl: '#',
    },
    {
        title: 'SkyCast',
        description: 'SkyCast is a user-friendly application designed to keep you informed about the weather in your favorite locations. Easily sign up to create a personalized profile and add locations that matter to you. Stay updated with real-time weather forecasts, alerts, and tips for each location you choose.',
        image: 'https://res.cloudinary.com/di22m4v3n/image/upload/q_auto,f_auto/v1732429877/portfolio/skycast_oyikkc.png',
        tags: ['React Native', 'Tailwind CSS', 'Firebase'],
        githubUrl: 'https://github.com/viniduminsara/SkyCast',
        liveUrl: 'https://github.com/viniduminsara/SkyCast/releases/tag/v1.0.0-beta',
    },
];

export const AllProjects = [
    {
        title: 'YelpCamp',
        description: 'YelpCamp is a full-stack web application designed for campground enthusiasts. It serves as a platform for users to explore, review, and share information about campgrounds from around the world. The application empowers users to discover new camping destinations, leave reviews based on their experiences, and contribute by adding new campgrounds.',
        image: 'https://res.cloudinary.com/di22m4v3n/image/upload/q_auto,f_auto/v1732361740/portfolio/yelpcamp_hjllcf.png',
        tags: ['Express', 'Node.js', 'MongoDB'],
        githubUrl: 'https://github.com/viniduminsara/YelpCamp',
        liveUrl: 'https://yelpcamp-g30m.onrender.com/',
    },
    {
        title: 'Shoes Management System',
        description: 'Hello Shoes Management System is a comprehensive web application designed to manage the operations of a shoe store. The system allows different types of users (regular and admin) to log in and perform specific actions based on their roles.',
        image: 'https://res.cloudinary.com/di22m4v3n/image/upload/q_auto,f_auto/v1732361737/portfolio/shoe-management-system_huhukc.png',
        tags: ['Java', 'Spring Boot', 'Tailwind CSS'],
        githubUrl: 'https://github.com/viniduminsara/Hello_Shoe_Management_System_Backend',
        liveUrl: '#',
    },
    {
        title: 'SkyCast',
        description: 'SkyCast is a user-friendly application designed to keep you informed about the weather in your favorite locations. Easily sign up to create a personalized profile and add locations that matter to you. Stay updated with real-time weather forecasts, alerts, and tips for each location you choose.',
        image: 'https://res.cloudinary.com/di22m4v3n/image/upload/q_auto,f_auto/v1732429877/portfolio/skycast_oyikkc.png',
        tags: ['React Native', 'Tailwind CSS', 'Firebase'],
        githubUrl: 'https://github.com/viniduminsara/SkyCast',
        liveUrl: 'https://github.com/viniduminsara/SkyCast/releases/tag/v1.0.0-beta',
    },
    {
        title: 'ClearLens',
        description: 'ClearLens is an e-commerce platform built to streamline the buying experience for spectacles. Users can create accounts to browse a diverse catalog of eyewear products, manage their favorites, and purchase securely. The platform is designed with a responsive UI for seamless navigation and integrates payment gateways to ensure secure transactions',
        image: 'https://res.cloudinary.com/di22m4v3n/image/upload/q_auto,f_auto/v1732361737/portfolio/clearlens_pcpggd.png',
        tags: ['React', 'Tailwind CSS', 'Express'],
        githubUrl: 'https://github.com/viniduminsara/ClearLens',
        liveUrl: '#',
    },
    {
        title: 'Salon Management System',
        description: 'The JavaFX standalone application for a salon management system is a comprehensive software solution designed to streamline and automate various aspects of running a salon. It provides a user-friendly interface that allows salon owners, managers, and staff.',
        image: 'https://res.cloudinary.com/di22m4v3n/image/upload/q_auto,f_auto/v1732361739/portfolio/salon-management-system_jsunht.png',
        tags: ['Java', 'JavaFX', 'MySQL'],
        githubUrl: 'https://github.com/viniduminsara/Salon_Management_System',
        liveUrl: '#',
    },
    {
        title: 'Chat Application',
        description: 'The chat application developed with Java socket programming is a versatile and efficient communication tool that allows users to exchange messages in real-time over a network. It leverages Java\'s socket programming capabilities to establish a reliable and secure connection between multiple clients. The chat application supports both text-based and multimedia-based messaging.',
        image: 'https://res.cloudinary.com/di22m4v3n/image/upload/q_auto,f_auto/v1732359639/portfolio/project03_image_gvncxl.svg',
        tags: ['Java', 'JavaFX'],
        githubUrl: 'https://github.com/viniduminsara/Group_Chat_Application',
        liveUrl: '#',
    },
    {
        title: 'Hostel Management System',
        description: 'The D24 Hostel Management System is a user-friendly and efficient standalone application built using JavaFX. This system is designed to streamline and simplify the management of hostels, making it an ideal solution for hostel administrators and staff.',
        image: 'https://res.cloudinary.com/di22m4v3n/image/upload/q_auto,f_auto/v1732361737/portfolio/hostel-management-system_izs3uf.png',
        tags: ['Java', 'JavaFX', 'MySQL'],
        githubUrl: 'https://github.com/viniduminsara/D24_Hostel_Management_System',
        liveUrl: '#',
    },
    {
        title: 'Connect-four game',
        description: 'The Connect Four game developed with JavaFX incorporates an AI player, offering an engaging and challenging single-player experience. This version of the classic strategy game allows players to test their skills against an intelligent computer opponent.JavaFX enhances the gaming experience by providing a visually appealing and interactive interface.',
        image: 'https://res.cloudinary.com/di22m4v3n/image/upload/q_auto,f_auto/v1732359626/portfolio/project02_image_dkasv2.svg',
        tags: ['Java', 'JavaFX'],
        githubUrl: 'https://github.com/viniduminsara/Connect_Four_Game',
        liveUrl: '#',
    },
    {
        title: 'QR Code Generator and Scanner',
        description: 'This QR Code Generating and Scanning Project in Java provides a convenient and efficient solution for users to create personalized QR codes and easily extract information from existing ones, making it applicable in a wide range of scenarios, including marketing, logistics, and information sharing.',
        image: 'https://res.cloudinary.com/di22m4v3n/image/upload/q_auto,f_auto/v1732359899/portfolio/project06_image_cwdldh.svg',
        tags: ['Java', 'JavaFX'],
        githubUrl: 'https://github.com/viniduminsara/QR_Generator_and_Scanner',
        liveUrl: '#',
    }
];
